print("="*55)
print("              🎓  Student Profile System          ")
print("="*55)
print()
print("            🚀 CREATE YOUR STUDENT PROFILE      ")
print()
print("="*55)
print("    Enter the details below              ")
print("="*55)
print()
name=input("Enter name:")
age=int(input("Enter Age:"))
roll_no=input("Enter Roll No:")
gender=input("Enter gender(F/M):")
branch=input("Enter Branch:")
year=int(input("Enter Current Year(1,2,3,4):"))
sem=int(input("Enter Sem:"))
sec=input("Enter Section:")
college=input("Enter College Name:")
ph=input("Enter Phone Number:")
email=input("Enter Email:")
city=input("Enter City:")
state=input("Enter state:")
cgpa=float(input("Enter CGPA:"))
skills=input("Enter Skills:")
dream_job=input("Enter Dream Job:")
dream_company=input("Enter Dream Company:")
print()
print("⏳ Generating Student Profile.....")
print()
print("="*50)
print("       Student Information System    ")
print("="*50)
print()
print("👤 Personal Details ")
print("-"*50)
print("Name               :",name.title())
print("Age                :",age)
print("Roll_no            :",roll_no)
print("Gender             :",gender.upper())
print()
print("🏫 College Details ")
print("-"*50)
print("Branch             :",branch.capitalize())
print("Year               :",year)
print("Sem                :",sem)
print("College            :",college.capitalize())
print("Section            :",sec.upper())
print("Cgpa               :",cgpa)
print()
print("📱 Contact Details")
print("-"*50)
print("Phone Number       :",ph)
print("Email              :",email.lower())
print("City               :",city.title())
print("State              :",state.title())
print()
print("🚀 Career Details ")
print("-"*50)
print("Skills             :",skills.title())
print("Dream Job          :",dream_job.title())
print("Dream Company      :",dream_company.title())
print()
print("="*50)